### ISSUE TITLE
Add Eureka to cluster

### ISSUE THREAD

**Issue by gqqnbig** [luoyuqi-lab/shine-cluster#129]
During #75  we found Eureka has hardware failure. Now that Eureka is fixed, we try to add it back.

**Comment by gqqnbig** [comment]
I followed up to [GPU服务器安装](https://github.com/gqqnbig/shine-cluster/wiki/GPU%E6%9C%8D%E5%8A%A1%E5%99%A8%E5%AE%89%E8%A3%85)


```
 NVIDIA-SMI 510.60.02    Driver Version: 510.60.02    CUDA Version: 11.6
```

Please check whether the GPU-related versions are good.

**Comment by luoyuqi-lab** [comment]
I think we need not change the driver version.

https://github.com/gqqnbig/shine-cluster/issues/122#issuecomment-1127255528

**Comment by luoyuqi-lab** [comment]
Eureka was added by @luoyuqi-lab on 2023.9.21, until now it works very well.
