### ISSUE TITLE
Different compute nodes can not share their cached data and models

### ISSUE THREAD

**Issue by o0mahan0o** [luoyuqi-lab/shine-cluster#167]
As titled, if the administrators have known it, please ignore it.
If there can be a solution, that would be nice. ^_^

**Comment by luoyuqi-lab** [comment]
Sometimes in some nodes, the mount of `shared` path fails. Caused by it.

Just [re-mount](https://github.com/luoyuqi-lab/shine-cluster/wiki/%E7%94%A8%E6%88%B7%E7%AE%A1%E7%90%86#%E5%A6%82%E6%9E%9C%E7%99%BB%E9%99%86%E8%8A%82%E7%82%B9%E7%9A%84shared%E6%8C%82%E8%BD%BD%E5%A4%B1%E6%95%88)
