### ISSUE TITLE
Reboot dagobah make its slurmd can not run.

### ISSUE THREAD

**Issue by luoyuqi-lab** [luoyuqi-lab/shine-cluster#172]
After reboot, dagobah can not run its slurmd daemon. I think the reason is one GPU is loss after reboot.

![image](https://user-images.githubusercontent.com/57832734/236122754-ca1268ae-b813-44b0-8351-1d5025d1ea5e.png)

Only 7 GPUs in the figure.

**Comment by luoyuqi-lab** [comment]
![image](https://user-images.githubusercontent.com/57832734/236122878-586fe472-0fac-4827-8fc6-35ee437eaa96.png)

**Comment by gqqnbig** [comment]
Is it fixed now?

**Comment by luoyuqi-lab** [comment]
![image](https://github.com/luoyuqi-lab/shine-cluster/assets/57832734/2b864ba5-3700-4ba2-9190-20b68e58ecbf)
![image](https://github.com/luoyuqi-lab/shine-cluster/assets/57832734/a7c80a51-d58d-4b3c-ae07-8680ae50377f)
#### Again, we lost 1 GPU then caused slurmd not to run, both in dagobah and hoth. I reboot machines by `sudo shutdown -r` in dagobah, and `sudo reboot` in hoth.

#### They must be some unknown bugs (maybe in codes or in physical machines) about GPU control, I have no idea now. 

### But I confirm that a physical reboot can make these two nodes become normal.

**Comment by luoyuqi-lab** [comment]
Lost GPU occurs again. In tatooine, only 3 GPUs but slurm still alive, after apply the bug-gpu, others can be normally used.
Use `lspci | grep -i nvidia` in hoth, `rev ff` means it is down, so there must problems in  **GPU 1c**.
![image](https://github.com/luoyuqi-lab/shine-cluster/assets/57832734/0a4d179c-3123-4d09-a20b-bad4ddabb067)
Tatooine seems normal but why 1 lost?
![image](https://github.com/luoyuqi-lab/shine-cluster/assets/57832734/1b2b2c3e-8257-4cc5-aed8-d8026f02ab7e)
Dagobah's problem may in **GPU 1a**.
![image](https://github.com/luoyuqi-lab/shine-cluster/assets/57832734/2726ab08-d5a9-4b98-8185-7723d2788fe5)

These things may be the clue why every remotely reboot makes 1 GPU lost.

**Comment by luoyuqi-lab** [comment]
Whenever I apply for a dagobah or hoth GPU, I am always given the bad one. So now I'm temporarily applying for the bad GPU to make sure other users can apply for a good card to run their tasks. Temporarily!

**Comment by luoyuqi-lab** [comment]
看起来很像，丢失一个显卡。[错误似乎也是一样的](https://forums.developer.nvidia.com/t/unable-to-determine-the-device-handle-for-gpu-000000-0-unknown-error/197974)。我准备详细检查nvidia log。
![image](https://github.com/luoyuqi-lab/shine-cluster/assets/57832734/d85c1d2f-7be4-486d-a460-fcc8e0740979)

**Comment by luoyuqi-lab** [comment]
dagobah上出问题的是0000:1a这张显卡。找到了可疑的东西，`May 26 19:01:41 dagobah kernel: NVRM: GPU 0000:1a:00.0: GPU has fallen off the bus.`
![image](https://github.com/luoyuqi-lab/shine-cluster/assets/57832734/df6fb99f-78ac-4a30-9ab7-2392761c1192)

**[有人说是供电，过热，pcie坏了，或者bios之类引起的](https://forums.developer.nvidia.com/t/how-to-solve-nvrm-gpu-000000-0-gpu-has-fallen-off-the-bus-completely/230923)。掉显卡这个问题似乎很常见。**

**Comment by luoyuqi-lab** [comment]
物理重启之后（远程shutdown -h now，然后进机房按按钮开关），所有显卡全部恢复，没有掉显卡。hoth和dagobah 8张，tatooine 4张。但是重启遇到了问题，dagobah风扇全转，并且没关机。hoth如图no.1，GPU持续模式守护进程关不掉，风扇没转，进机房按按钮关的。tatooine重启正常。hoth和dagobah肯定有潜在的问题，系统或者硬件。
![406a8c601dc97b52cdec0d6d373bd00](https://github.com/luoyuqi-lab/shine-cluster/assets/57832734/b8834a40-eba0-4bdf-a067-182f821e9d6f)
![image](https://github.com/luoyuqi-lab/shine-cluster/assets/57832734/c9d3fb8d-c744-4b53-b901-fc5fbf531d6e)
![image](https://github.com/luoyuqi-lab/shine-cluster/assets/57832734/06cdfed5-55e2-487d-8e60-d209ebf1bc3a)
![image](https://github.com/luoyuqi-lab/shine-cluster/assets/57832734/36df43de-2d8a-4d7b-bb71-c2b2115fe796)

**Comment by luoyuqi-lab** [comment]
看到了同样的[问题](https://deeptalk.lambdalabs.com/t/unable-to-determine-the-device-handle-for-gpu000000-0-unknown-error/3883)，查看nvidia-bug-report.log.gz暂时没找到线索。对于tatooine，准备寻求lambda客服的帮助。

**Comment by gqqnbig** [comment]
> But I confirm that a physical reboot can make these two nodes become normal.

Rather than physical reboot, try https://manpages.ubuntu.com/manpages/trusty/man8/nvram-wakeup.8.html

**Comment by gqqnbig** [comment]
The so-called 'physical reboot' coincides [cold reboot](https://en.wikipedia.org/wiki/Reboot).

Never underestimate a concept learned in your teens!

**Comment by lyulyul** [comment]
dagobah frequent problems with draining and dropping the video card, the possible causes of failure speculation, one is the frequent dropping of that video card is problematic, the second may be the chassis invasion. Instead of going to the server room to force a shutdown to recover, you can control the shutdown remotely. Install IPMIView on the client, and the same can be done remotely by switching off and restoring the dagobah temporarily. IPMIView can remotely view the status of the server, temperature, power, and can be visualized, it is a very good tool.
following URL:
https://github.com/luoyuqi-lab/shine-cluster/wiki/Power-Cycle-Server

**Comment by lyulyul** [comment]
Dagobah is like a weathered but fighting old dog, we need to take more care of his health.
![1708571549339](https://github.com/luoyuqi-lab/shine-cluster/assets/145745659/e489bc4b-e602-4c62-b459-274d7debffab)

**Comment by lyulyul** [comment]
Please check the wiki page for 'physically reboot' a failed machine https://github.com/luoyuqi-lab/shine-cluster/wiki/Power-Cycle-Server

With all due respect, I recommend to close this aged stubborn issue. If you have separate concerns, please create a new issue.
